---
- hosts: {{server_name}}
  become: true
  tasks:
  - name: Install httpd 
    yum:
     name: httpd
     state: installed
  - name: Activate httpd 
    service:
      name: httpd
      state: started
      enabled: yes
